- name: Install and configure NGINX
  hosts: all
  become: true
  tasks:
    - name: Install nginx
      ansible.builtin.package:
        name: nginx
        state: present

    - name: Create landing page
      ansible.builtin.copy:
        content: |
          <html>
            <head><title>Demo App</title></head>
            <body>
              <div class="env">Environment: {{ app_environment | default("default environment") }}</div>
              <h1 style="text-align:center; margin-top:20%;"> {{ app_message | default("Welcome to the Demo App!") }}</h1>
              <div style="text-align:center;"><img src="https://picsum.photos/400" /></div>
            </body>
          </html>
        dest: /usr/share/nginx/html/index.html
        mode: '0644'

    - name: Start and enable nginx
      ansible.builtin.service:
        name: nginx
        state: started
        enabled: true

    - name: Set deployment complete flag
      ansible.builtin.set_stats:
        data:
          nginx_deployed: true
